//Character types
export const CHARACTERS_LIST_START = 'CHARACTERS_LIST_START';
export const CHARACTERS_LIST_SUCCESS = 'CHARACTERS_LIST_SUCCESS';
export const CHARACTERS_LIST_FAILURE = 'CHARACTERS_LIST_FAILURE';


//Films types
export const FILMS_LIST_START = 'FILMS_LIST_START';
export const FILMS_LIST_SUCCESS = 'FILMS_LIST_SUCCESS';
export const FILMS_LIST_FAILURE = 'FILMS_LIST_FAILURE';

